server:
  port: 60070
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: teams
      host: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  security:
    enabled: false
  health:
    defaults: true
    sensitive: true
  endpoints:
    web:
      expose: "*"
    health:
      show-details: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT

amqp:
  teams:
    queue:
      created:
        request: team_created_queue
      updated:
        request: team_updated_queue
      consultant:
        added:
          request: consultant_added_team_queue
        updated:
          request: consultant_updated_team_queue
        removed:
          request: consultant_removed_team_queue
    exchange:
      created:
        team: teams
      updated:
        team: teams
      consultant:
        added:
          team: teams_topic
        updated:
          team: teams
        removed:
          team: teams
    key:
      created:
        request: team_created
      updated:
        request: team_updated
      consultant:
        added:
          request: consultant_added_team
        updated:
          request: consultant_updated_team
        removed:
          request: consultant_removed_team
      
clients:
  service: CLIENTS

consultants:
  service: CONSULTANTS
  
projects:
  service: PROJECTS
  
skills:
  service: SKILLS

sites:
  service: SITES  
